coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default: on
    patch:
      default: on
    changes:
      default: off

  ignore:
  - "examples/scripts/*"
  - "examples/sessions/*"
  - "examples/src/*"
  - ".*/usr/.*"
  - ".*/collab/.*"

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

