language: c
      
cache:
  directories:
    - $HOME/local

sudo: required

compiler:
  - gcc-4.8

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libelf-dev
      - libdwarf-dev
      - libboost-all-dev
      - swig
      - graphviz
      - munge
      - gfortran
      - gdb

env:
  global:
    - export PATH=$HOME/local/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  - eval $(./scripts/travis-dep-builder.sh --printenv)
  # travis has a 50 minute timeout for any single command, so we break up the build so it will partially cache as needed:
#  - ./scripts/travis-dep-builder.sh --cachedir=$HOME/local/.cache --components=ompi
#  - ./scripts/travis-dep-builder.sh --cachedir=$HOME/local/.cache --components=other
#  - ./scripts/travis-dep-builder.sh --cachedir=$HOME/local/.cache --components=dyninst

script:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - ls -l $HOME/local
  - ls -l $HOME/local/lib
  - ls -l $HOME/local/bin
  - ls -l $HOME/local/etc
  - ls -l $HOME/local/include
  - cd $HOME/build/LLNL/STAT
  - ./bootstrap
  - export LDFLAGS=-Wl,-no-as-needed
  - ./configure --prefix=$HOME/stat --with-stackwalker=$HOME/local/dyninst --with-mrnet=$HOME/local --with-graphlib=$HOME/local --with-launchmon=$HOME/local --enable-debug || cat config.log
  - make && make install

after_script:
  - ls -l $HOME/stat/bin
  - $HOME/stat/bin/stat-cl -h
  - export STAT_XPLAT_RSH=rsh
  - export XPLAT_RSH=rsh
  - export XPLAT_RSH_ARGS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  - ssh-keygen -N '' -t rsa -f $HOME/.ssh/id_rsa
  - cat $HOME/.ssh/id_rsa.pub > $HOME/.ssh/authorized_keys
  - ssh-keygen -N '' -t dsa -f $HOME/.ssh/id_dsa
  - cat $HOME/.ssh/id_dsa.pub >> $HOME/.ssh/authorized_keys
#  - rsh `hostname` hostname & export RSHPID=$! ; sleep 5; kill -9 $RSHPID
  - rsh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no `hostname` hostname  & export RSHPID=$! ; sleep 5; kill -9 $RSHPID
  - echo -e "Host $HOSTNAME\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  - export MRNET_OUTPUT_LEVEL=5
  - echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
  - $HOME/stat/share/stat/examples/bin/rank_test 10 & $HOME/stat/bin/stat-cl -s 2 -l FE -l BE -L $HOME -I $!
  - cat stat_results/output.0000/output.0000.top
  - cat stat_results/output.0000/output.0000.fulltop
#  - cat $HOME/$HOSTNAME.STAT.log
#  - cat $HOME/$HOSTNAME.STATD.log
  - cat stat_results/output.0000/00_output.0000.2D.dot
  - cat stat_results/output.0000/01_output.0000.2D.dot
  - cat stat_results/output.0000/02_output.0000.2D.dot
  - cat stat_results/output.0000/03_output.0000.2D.dot
  - cat stat_results/output.0000/04_output.0000.3D.dot
  - which mpirun
  - export LMON_FE_ENGINE_TIMEOUT=20
  - mpirun -n 4 $HOME/stat/share/stat/examples/bin/mpi_ringtopo 40 & $HOME/stat/bin/stat-cl -s 2 -l FE -l BE -L $HOME $!
  - wait $!
  - cat stat_results/mpi_ringtopo.0000/mpi_ringtopo.0000.top
  - cat stat_results/mpi_ringtopo.0000/mpi_ringtopo.0000.fulltop
  - cat stat_results/mpi_ringtopo.0000/00_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/01_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/02_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/03_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/04_mpi_ringtopo.0000.3D.dot
  - $HOME/stat/bin/stat-cl -s 5 -l FE -l BE -L $HOME -C mpirun -n 4 $HOME/stat/share/stat/examples/bin/mpi_ringtopo 40
  - ps x | grep mpirun | grep -v grep | cut -f 1 -d " " | xargs kill -18
  - sleep 40
  - cat stat_results/mpi_ringtopo.0001/mpi_ringtopo.0001.top
  - cat stat_results/mpi_ringtopo.0001/mpi_ringtopo.0001.fulltop
  - cat stat_results/mpi_ringtopo.0001/00_mpi_ringtopo.0001.2D.dot
  - cat stat_results/mpi_ringtopo.0001/01_mpi_ringtopo.0001.2D.dot
  - cat stat_results/mpi_ringtopo.0001/02_mpi_ringtopo.0001.2D.dot
  - cat stat_results/mpi_ringtopo.0001/03_mpi_ringtopo.0001.2D.dot
  - cat stat_results/mpi_ringtopo.0001/04_mpi_ringtopo.0001.3D.dot
#  The script test currently fails as openmpi does not support reattach when launched under a debugger (https://github.com/open-mpi/ompi/issues/3178)
#  The script test may also hang with openmpi-2.0.3. This appears to be a race condition when deleting the stat_fe object
  - $HOME/stat/bin/stat-script $HOME/stat/share/stat/examples/bin/script_test.py || echo "failed with $?"
