language: c
      
cache:
  directories:
    - $HOME/local

sudo: required

#dist: trusty

compiler:
  - gcc-4.8

addons:
  apt:
#    hostname: travistest
#    sources:
#      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - libelf-dev
      - libdwarf-dev
      - libboost-all-dev
      - swig
      - graphviz
      - munge
# note that we need to build openmpi and STAT's examples with gfortran installed
# however, having this package causes dyninst to fail to build
#      - gfortran
      - gdb

env:
  global:
    - export PATH=$HOME/local/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
    - export CC=gcc-4.8
    - export CXX=g++-4.8

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CC="gcc-4.8"
  - export CXX="g++-4.8"
  - eval $(./scripts/travis-dep-builder.sh --printenv)
  - ./scripts/travis-dep-builder.sh --cachedir=$HOME/local/.cache

script:
  - ls -l $HOME/local
  - ls -l $HOME/local/lib
  - ls -l $HOME/local/bin
  - ls -l $HOME/local/include
  - cd $HOME/build/LLNL/STAT
  - ./bootstrap
  - export LDFLAGS=-Wl,-no-as-needed
  - ./configure --prefix=$HOME/stat --with-stackwalker=$HOME/local --with-mrnet=$HOME/local --with-graphlib=$HOME/local --with-launchmon=$HOME/local --with-libdwarf=$HOME/local --with-libiberty=$HOME/local --enable-debug || cat config.log
  - make && make install

after_script:
  - ls -l $HOME/stat/bin
  - $HOME/stat/bin/stat-cl -h
  - export STAT_XPLAT_RSH=rsh
  - export XPLAT_RSH=rsh
  - export XPLAT_RSH_ARGS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  - ssh-keygen -N '' -t rsa -f $HOME/.ssh/id_rsa
  - cat $HOME/.ssh/id_rsa.pub > $HOME/.ssh/authorized_keys
  - ssh-keygen -N '' -t dsa -f $HOME/.ssh/id_dsa
  - cat $HOME/.ssh/id_dsa.pub >> $HOME/.ssh/authorized_keys
  - cat $HOME/.ssh/authorized_keys
#  - rsh `hostname` hostname & export RSHPID=$! ; sleep 5; kill -9 $RSHPID
  - rsh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no `hostname` hostname  & export RSHPID=$! ; sleep 5; kill -9 $RSHPID
  - echo -e "Host $HOSTNAME\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cat ~/.ssh/config
  - cat ~/.ssh/known_hosts
#  - export MRNET_OUTPUT_LEVEL=5
  - echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
  - $HOME/stat/share/stat/examples/bin/rank_test 10 & $HOME/stat/bin/stat-cl -s 2 -l FE -l BE -L $HOME -I $!
  - cat stat_results/output.0000/output.0000.top
  - cat stat_results/output.0000/output.0000.fulltop
  - cat $HOME/$HOSTNAME.STAT.log
  - cat $HOME/$HOSTNAME.STATD.log
  - cat stat_results/output.0000/00_output.0000.2D.dot
  - cat stat_results/output.0000/01_output.0000.2D.dot
  - cat stat_results/output.0000/02_output.0000.2D.dot
  - cat stat_results/output.0000/03_output.0000.2D.dot
  - cat stat_results/output.0000/04_output.0000.3D.dot
  - which mpirun
  - export LMON_FE_ENGINE_TIMEOUT=20
  - mpirun -n 4 $HOME/stat/share/stat/examples/bin/mpi_ringtopo 40 & $HOME/stat/bin/stat-cl -s 2 -l FE -l BE -L $HOME $!
  - wait $!
  - cat stat_results/mpi_ringtopo.0000/mpi_ringtopo.0000.top
  - cat stat_results/mpi_ringtopo.0000/mpi_ringtopo.0000.fulltop
  - cat stat_results/mpi_ringtopo.0000/00_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/01_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/02_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/03_mpi_ringtopo.0000.2D.dot
  - cat stat_results/mpi_ringtopo.0000/04_mpi_ringtopo.0000.3D.dot
  - cat $HOME/$HOSTNAME.STAT.log
  - echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
  - $HOME/stat/bin/stat-cl -s 5 -l FE -l BE -L $HOME -C /home/travis/local/bin/mpirun -n 4 $HOME/stat/share/stat/examples/bin/mpi_ringtopo 40
  - ls -l $HOME/$HOSTNAME.STAT.log
  - ls -l $HOME/$HOSTNAME.STATD.log
  - cat $HOME/$HOSTNAME.STAT.log
  - cat $HOME/$HOSTNAME.STATD.log
  - sleep 40
#  The script test currently fails as openmpi does not support reattach when launched under a debugger (https://github.com/open-mpi/ompi/issues/3178)
  - echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
  - $HOME/stat/bin/stat-script $HOME/stat/share/stat/examples/bin/script_test.py
